"""Create a notebook whose saved outputs are generated by actual execution."""
from pathlib import Path
import nbformat as n
R=Path(__file__).resolve().parent;cells=[]
def md(s):cells.append(n.v4.new_markdown_cell(s))
def code(s):cells.append(n.v4.new_code_cell(s))
md("# DL069 可执行实验\n\n代码单元按序真实运行，输出保存在notebook_outputs。")
code("from pathlib import Path\nimport sys,json,numpy as np,torch\nimport experiment as e\nimport matplotlib.pyplot as plt\nfrom io import BytesIO\nfrom IPython.display import Image,display\ndef show(fig):\n    b=BytesIO();fig.savefig(b,format='png',dpi=140,bbox_inches='tight');display(Image(data=b.getvalue()));plt.close(fig)\ntorch.set_num_threads(1)\nprint({'python':sys.version.split()[0],'torch':torch.__version__,'device':'CPU'})")
md('## 数据与随机源')
code('x,y=e.data();print(x.shape,y.shape,e.CONFIG)')
md('## 完整语义测试')
code("import unittest,test_experiment\nz=unittest.TextTestRunner().run(unittest.defaultTestLoader.loadTestsFromModule(test_experiment))\nif not z.wasSuccessful():raise RuntimeError('tests failed')")
md('## 实际建立检查点与资产清单')
code('r=e.run("notebook_outputs");print({k:r[k] for k in ["resume_max_parameter_gap","weights_only_max_parameter_gap","metrics","simulated_tamper_detected"]})')
md('## 直接画出本次训练轨迹')
code('fig,ax=plt.subplots(figsize=(8,3))\nfor k in r["histories"]:\n    h=r["histories"][k];ax.plot([a["epoch"] for a in h],[a["train_loss"] for a in h],label=k)\nax.axvline(12,color="gray");ax.set(xlabel="Epoch",ylabel="Train CE");ax.legend();show(fig)')
md('## 重新加载三个终点计算指标')
code('x,y=e.data()\nfor name,key in [("continuous","continuous"),("resumed","resumed"),("weights_only","weights_only")]:\n    ck=torch.load(f"notebook_outputs/{name}_epoch24.pt",weights_only=True);m=e.model();m.load_state_dict(ck["model"]);z=e.assess(m,x,y)\n    np.testing.assert_allclose(z["loss"],r["metrics"][key]["loss"],rtol=0,atol=1e-7);print(name,z)\nmanifest=json.loads(Path("notebook_outputs/asset_manifest.json").read_text())\nif e.verify_assets("notebook_outputs",manifest):raise RuntimeError("asset hash mismatch")\nprint("six assets verified")')
md('## 精确一致与不同轨迹')
code('fig,ax=plt.subplots(figsize=(7,3));ax.bar(["full resume","weights only"],[r["resume_max_parameter_gap"],r["weights_only_max_parameter_gap"]]);ax.set(ylabel="Maximum parameter gap");show(fig)\nprint(r["limits"])')
nb=n.v4.new_notebook(cells=cells,metadata={'kernelspec':{'display_name':'Python 3','language':'python','name':'python3'},'language_info':{'name':'python'}})
n.write(nb,R/'experiment.ipynb')
