name: dl-unit-037
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cpu
      - torch==2.7.1+cpu
      - numpy==2.3.5
      - matplotlib==3.10.8
      - nbformat==5.11.1
      - ipykernel==7.4.0
      - jupyterlab
