"""Create a notebook whose saved outputs are generated by actual execution."""
from pathlib import Path
import nbformat as n
R=Path(__file__).resolve().parent;cells=[]
def md(s):cells.append(n.v4.new_markdown_cell(s))
def code(s):cells.append(n.v4.new_code_cell(s))
md("# DL068 可执行实验\n\n代码单元按序真实运行，输出保存在notebook_outputs。")
code("from pathlib import Path\nimport sys,json,numpy as np,torch\nimport experiment as e\nimport matplotlib.pyplot as plt\nfrom io import BytesIO\nfrom IPython.display import Image,display\ndef show(fig):\n    b=BytesIO();fig.savefig(b,format='png',dpi=140,bbox_inches='tight');display(Image(data=b.getvalue()));plt.close(fig)\ntorch.set_num_threads(1)\nprint({'python':sys.version.split()[0],'torch':torch.__version__,'device':'CPU'})")
md('## 先手算分位数')
code('print(np.quantile([1,2,3,4,100],[.5,.95],method="linear"))')
md('## 运行合同与语义测试')
code("import unittest,test_experiment\nz=unittest.TextTestRunner().run(unittest.defaultTestLoader.loadTestsFromModule(test_experiment))\nif not z.wasSuccessful():raise RuntimeError('tests failed')")
md('## 真实训练导出重载与计时')
code('r=e.run("notebook_outputs")\nprint({k:r[k] for k in ["accuracy","wrong_preprocessing_accuracy","export_checks","requests"]})')
md('## 观察全部原始计时')
code('fig,ax=plt.subplots(figsize=(8,3))\nfor key in r["timings"]:\n    v=np.sort(r["timings"][key]["samples_us"]);ax.plot(v,np.arange(1,len(v)+1)/len(v),label=key)\nax.set(xlabel="Call time (us)",ylabel="Empirical CDF",title="CPU local calls, no network");ax.legend();show(fig)')
md('## 检查保存的权重和导出图')
code('a=np.load("notebook_outputs/data.npz");state=torch.load("notebook_outputs/model.pt",weights_only=True)\nm=e.Model(state["mean"],state["scale"]);m.load_state_dict(state);m.eval()\nexported=torch.export.load("notebook_outputs/model_batch32.pt2").module()\nx=torch.from_numpy(a["x"][768:])\nwith torch.inference_mode():\n    z=m(x);g=torch.cat([exported(x[i:i+32]) for i in range(0,len(x),32)])\ntorch.testing.assert_close(z,g,rtol=1e-5,atol=1e-5)\nprint("all 384 exported predictions checked",float((z-g).abs().max()))')
md('## 区分吞吐与延迟')
code('fig,ax=plt.subplots(figsize=(8,3));keys=list(r["timings"])\nax.bar(keys,[r["timings"][k]["throughput_examples_per_second"] for k in keys]);ax.set(ylabel="Examples / second",title="Closed-loop model throughput only");show(fig)\nprint(r["limits"])')
nb=n.v4.new_notebook(cells=cells,metadata={'kernelspec':{'display_name':'Python 3','language':'python','name':'python3'},'language_info':{'name':'python'}})
n.write(nb,R/'experiment.ipynb')
