"""Create a notebook whose saved outputs are generated by actual execution."""
from pathlib import Path
import nbformat as n
R=Path(__file__).resolve().parent;cells=[]
def md(s):cells.append(n.v4.new_markdown_cell(s))
def code(s):cells.append(n.v4.new_code_cell(s))
md("# DL070 可执行实验\n\n代码单元按序真实运行，输出保存在notebook_outputs。")
code("from pathlib import Path\nimport sys,json,numpy as np,torch\nimport experiment as e\nimport matplotlib.pyplot as plt\nfrom io import BytesIO\nfrom IPython.display import Image,display\ndef show(fig):\n    b=BytesIO();fig.savefig(b,format='png',dpi=140,bbox_inches='tight');display(Image(data=b.getvalue()));plt.close(fig)\ntorch.set_num_threads(1)\nprint({'python':sys.version.split()[0],'torch':torch.__version__,'device':'CPU'})")
md('## 先读取固定计划')
code('print(json.dumps(e.PLAN,ensure_ascii=False,indent=2))')
md('## 运行配对初始化与数学测试')
code("import unittest,test_experiment\nz=unittest.TextTestRunner().run(unittest.defaultTestLoader.loadTestsFromModule(test_experiment))\nif not z.wasSuccessful():raise RuntimeError('tests failed')")
md('## 实际执行20个训练分支')
code('r=e.run("notebook_outputs");print(r["summary"]);print(r["paired_dropout_minus_baseline"]);print(r["budget"])')
md('## 配对差来自每个种子')
code('d=r["paired_dropout_minus_baseline"];fig,ax=plt.subplots(figsize=(7,3));ax.scatter(e.SEEDS,d["values"]);ax.axhline(0,color="gray");ax.set(xlabel="Initialization seed",ylabel="Dropout minus baseline test NLL");show(fig)')
md('## 所有checkpoint重载检查')
code('x,y=e.data()\nfor row in r["runs"]:\n    ck=torch.load(f"notebook_outputs/{row[\'mode\']}_seed{row[\'seed\']}.pt",weights_only=True);m=e.model(ck["p"]);m.load_state_dict(ck["state_dict"]);z=e.evaluate(m,x[320:],y[320:])\n    np.testing.assert_allclose(z["nll"],row["test"]["nll"],rtol=0,atol=1e-7)\nprint("20 checkpoints independently reloaded")')
md('## 看见选择规则与限制')
code('fig,ax=plt.subplots(figsize=(8,3))\nfor mode in e.MODES:\n    row=next(a for a in r["runs"] if a["seed"]==11 and a["mode"]==mode);ax.plot([h["epoch"] for h in row["history"]],[h["validation_nll"] for h in row["history"]],label=mode)\nax.set(xlabel="Update",ylabel="Validation NLL");ax.legend(loc="upper center",bbox_to_anchor=(0.5,1.28),ncol=4);show(fig)\nprint(r["limits"])')
nb=n.v4.new_notebook(cells=cells,metadata={'kernelspec':{'display_name':'Python 3','language':'python','name':'python3'},'language_info':{'name':'python'}})
n.write(nb,R/'experiment.ipynb')
